---
title: "Politeness S2 predictions"
output: html_notebook
---


```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(rwebppl)
library(jsonlite)
library(magrittr)
library(ggthemes)
library(forcats)
# set path to working dir
# local.path <- "~/Documents/research/polgrice/"
local.path <- "~/Documents/Research/polgrice_GIT/"
```

```{r}
rsaModel <-'
var utterances = [
  "yes_terrible","yes_bad","yes_good","yes_amazing",
  "not_terrible","not_bad","not_good","not_amazing"
  ];

var states = [0, 1, 2, 3];

var statePrior = function(){
  return uniformDraw(states);
};

var isNegation = function(utt){
  return (utt.split("_")[0] == "not")
};

var marginalize = function(dist, key){
	return Infer({method: "enumerate"}, function(){ sample(dist)[key] })
}

var cost_yes = 1;
var cost_neg = 1.5;
var speakerOptimality = 5;

var round = function(x){
	return Math.round(x * 100) / 100
}

var weightBins = map(round, _.range(0,1, 0.05))
var phiWeights = repeat(weightBins.length, function(){1})

var uttCosts = map(function(u) {
	return isNegation(u) ? Math.exp(-cost_neg) : Math.exp(-cost_yes)
}, utterances)

var utterancePrior = Infer({method: "enumerate"}, function(){
  return utterances[discrete(uttCosts)]
});

var literalSemantics = { // 0 -> 0.001, 1 -> 0.999
  "state": [0, 1, 2, 3],
  "not_terrible": [0.001, 0.353, 0.980, 0.863],
  "not_bad": [0.020, 0.157, 0.999, 0.902],
  "not_good": [0.961, 0.863, 0.039, 0.020],
  "not_amazing": [0.961, 0.980, 0.627, 0.039],
  "yes_terrible": [0.961, 0.627, 0.039, 0.039],
  "yes_bad": [0.980, 0.882, 0.039, 0.020],
  "yes_good": [0.001, 0.020, 0.941, 0.999],
  "yes_amazing": [0.001, 0.001, 0.216, 0.980]
};


var meaning = function(words, state){
  return flip(literalSemantics[words][state - 1]);
};

var listener0 = cache(function(utterance) {
  Infer({method: "enumerate"}, function(){
	var state = uniformDraw(states);
    var m = meaning(utterance, state);
    condition(m);
    return state;
	})
}, 10000);

var speaker1 = cache(function(state, phi) {
  Infer({method: "enumerate"}, function(){

    var utterance = sample(utterancePrior);
    var L0 = listener0(utterance);

    var epistemicUtility = L0.score(state);
    var socialUtility = expectation(L0, function(s){return s});
    var eUtility = phi*epistemicUtility;
    var sUtility = (1-phi)*socialUtility;
    var speakerUtility = eUtility+sUtility;

    factor(speakerOptimality*speakerUtility);

    return utterance;
	})
}, 10000);

var listener1 = cache(function(utterance) {
  Infer({method: "enumerate"}, function(){

   var phi = categorical ({vs: weightBins, ps: phiWeights})
    var state = uniformDraw(states);

   var S1 = speaker1(state, phi)
   observe(S1, utterance)

   return {
     state: state,
     phi: phi
   }

 })
}, 10000);

var speaker2 = cache(function(state, s1_phi, selfpres_phi, social_phi, informative_phi) {
  Infer({method: "enumerate"}, function(){

	 var utterance = sample(utterancePrior);

   var L1 = listener1(utterance)
	  var L1_goal = marginalize(L1, "phi");
	  var L1_state = marginalize(L1, "state");

    var epistemicUtility = L1_state.score(state);
    var selfpresUtility = L1_goal.score(s1_phi);
   var socialUtility = expectation(L1_state, function(s){return s});

  var speakerMixedUtility = informative_phi*epistemicUtility +
                            selfpres_phi*selfpresUtility +
                            social_phi*socialUtility

//	factor(speakerOptimality * speakerMixedUtility); // triple mixture
//	factor(speakerOptimality * informative_phi*epistemicUtility); // true informative only
//	factor(speakerOptimality * social_phi*socialUtility); // true social only
//	factor(speakerOptimality * selfpres_phi*selfpresUtility); // self-presentational only
//	factor(speakerOptimality * (social_phi*socialUtility + selfpres_phi*selfpresUtility)); // true social + self pres
	factor(speakerOptimality * (informative_phi*epistemicUtility + selfpres_phi*selfpresUtility)); // true informative + self pres
	factor(speakerOptimality * (informative_phi*epistemicUtility + social_phi*socialUtility)); // true informative + true social



   return {negation: isNegation(utterance),
            utterance: utterance,
            s1_phi: s1_phi, 
            selfpres_phi: selfpres_phi, 
            social_phi: social_phi, 
            informative_phi: informative_phi, 
            cost_neg: cost_neg,
            speakerOptimality: speakerOptimality
}

 })
}, 10000);

//listener1("not_amazing")
speaker2(1, 0.1, 0.01, 0.6, 0.4);
'

# l1.rs <- webppl(rsaModel) %>%
#   mutate(state = factor(state))
# 
# ggplot(l1.rs, aes( x = phi, y = prob, color = state, group = state))+
#   geom_line()

s2.informative_social <- webppl(rsaModel) %>%
  mutate(model = "informative + social") %>%
  separate(utterance, c("positivity","utterance")) %>%
  mutate(utterance = fct_relevel(utterance, 
                                "terrible", "bad", "good", "amazing"))

s2.informative_social %>% 
  ggplot(., aes( x = utterance, y = prob, 
                 color = positivity, group = positivity))+
  geom_line()+
  theme_few()+
  scale_color_solarized()
```

```{r}
# l1.all2 <- l1.all2 %>% mutate(prior = factor(prior, levels = c("neither", "L0_only", "L1_only", "both")))
# 
# ggplot(l1.all2, aes( x = phi, y = prob, color = state, group = state))+
#   geom_line() +
#   facet_grid(prior~.)+
#   ggtitle("L1 prediction on phi given \"not amazing\", \n faceted by state prior setting")
# 
# ggplot(l1.all %>%
#          group_by(state, prior) %>%
#          summarise(prob = sum(prob)), 
#        aes( x = state, y = prob, fill = state, group = state))+
#   geom_bar(position=position_dodge(), stat = "identity") +
#   facet_grid(prior~.)+
#   ggtitle("L1 prediction on state given \"not terrible\", \n faceted by state prior setting")

```

```{r}
speakerModel <- '
var speaker2 = cache(function(state, truthiness) {
  Infer({method: "enumerate"}, function(){

	 var utterance = sample(utterancePrior);
	 var intendedGoals = {phi: truthiness}

   var L1 = listener1(utterance)

   factor(speakerOptimality2 * L1.score({
              "state":state,
              "goals":intendedGoals
    }))

   return {negation: isNegation(utterance),
            utterance: utterance}

 })
}, 10000);

speaker2(1, 0.4);
'

fullModel = paste(rsaModel, speakerModel, sep="\n\n")

s2.rs <- webppl(fullModel)
```

```{r}
s2.predictions <- data.frame()
for (s in c(1,2,3,4,5)){
  
  for (w in c(0.1, 0.5, 0.9)) {
    inputData <- list(
      state = s,
      weight = w
    )
    
    s2 <- webppl(rsaModel, data = inputData, data_var = "inputData")
    
    s2.neg <- s2 %>% 
      filter(negation) %>% 
      summarize(negation = sum(prob)) %>%
      mutate(state = s, weight = w)
    
    s2.predictions <- bind_rows(s2.predictions, s2.neg)
  }
}
```


```{r}
s2.predictions %>% 
  mutate(
    weight = factor(weight, levels = c(0.9, 0.1, 0.5),
                         labels = c("informative", "social", "both"))
  ) %>%
  ggplot(., aes( x = state, y = negation, 
                 color = weight, group = weight))+
  geom_line()+
  theme_few()+
  scale_color_solarized()
```

