---
title: "Figure for L2 goal inference given state and utterance"
author: "Erica Yoon"
date: "Jan 16 2016"
output: html_document
---

```{r warning=FALSE, message=FALSE, echo=FALSE}
rm(list = ls())
library(jsonlite)
library(ggplot2)
library(tidyr)
library(dplyr)
library(binom)
library(bootstrap)
source("/Users/ericang/Documents/Research/polgrice_GIT/experiment/data_analysis/helper/useful.R")

raw.data.path <- "/Users/ericang/Documents/Research/polgrice_GIT/experiment/exp_versions/5_L2_G/production-results/"

## LOOP TO READ IN FILES
all.data <- data.frame()
files <- dir(raw.data.path,pattern="*.json")

for (file.name in files) {
  
  ## these are the two functions that are most meaningful
  json_file <- readLines(paste(raw.data.path,file.name,sep=""))
  json_file_str = paste(json_file, collapse = "")
  json_file_str = gsub(",}", "}", json_file_str)
  jso = jsonlite::fromJSON(json_file_str)
  jso$answers$data$people <- NULL
  jso1 <- data.frame(jso)
  jso1$subid <- substring(file.name, 1, 6)
  
  ## now here's where data get bound together
  all.data <- rbind(all.data, jso1)
}
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
rearr <- all.data %>%
  select(subid, num_range("answers.data.goal", 0:2)) %>%
  distinct(subid) %>%
  gather(goal_order, goal, num_range("answers.data.goal", 0:2)) %>%
  mutate(goal_order = substr(goal_order, 18, 18))

d <- all.data %>%
  select(subid, answers.data.order, answers.data.knowledge, answers.data.domain, answers.data.state, answers.data.utterance, num_range("answers.data.goalProb", 0:2)) %>%
  gather(goal_order, goal_prob, num_range("answers.data.goalProb", 0:2)) %>%
  mutate(goal_order = substr(goal_order, 22, 22))

detach(package:dplyr)
library(plyr)
d <- join(d, rearr)

detach(package:plyr)
library(dplyr)
d <- d %>%
  mutate(trial = answers.data.order) %>%
  mutate(item = answers.data.domain) %>%
  mutate(true_state = substr(answers.data.state, 6, 6)) %>%
  mutate(utterance = answers.data.utterance) %>%
  mutate(knowledge = answers.data.knowledge) %>%
  select(subid, trial, knowledge, true_state, utterance, goal, goal_prob)

d$subid <- as.factor(d$subid)
d$trial <- as.numeric(d$trial)
d$true_state <- as.factor(d$true_state) 
d$knowledge <- as.factor(d$knowledge)
d$utterance <- as.factor(d$utterance)
d$goal <- as.factor(d$goal)
d$goal_prob <- as.numeric(d$goal_prob)

d$utterance <- ordered(d$utterance, levels = c("terrible", "bad", "okay", "good", "amazing"))
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
## for bootstrapping 95% confidence intervals
theta <- function(x,xdata,na.rm=T) {mean(xdata[x],na.rm=na.rm)}
ci.low <- function(x,na.rm=T) {
  mean(x,na.rm=na.rm) - quantile(bootstrap(1:length(x),1000,theta,x,na.rm=na.rm)$thetastar,.025,na.rm=na.rm)}
ci.high <- function(x,na.rm=T) {
  quantile(bootstrap(1:length(x),1000,theta,x,na.rm=na.rm)$thetastar,.975,na.rm=na.rm) - mean(x,na.rm=na.rm)}

# goal_prob ~ true_state + utterance + goal
mss <- d %>%
  group_by(true_state, utterance, goal, subid) %>%
  summarize(
            goal_prob = mean(goal_prob, na.rm=TRUE)
          )
ms <- aggregate(goal_prob ~ true_state + utterance + goal, mss, mean)
ms$cih <- aggregate(goal_prob ~ true_state + utterance + goal, mss, ci.high)$goal_prob
ms$cil <- aggregate(goal_prob ~ true_state + utterance + goal, mss, ci.low)$goal_prob
```

## Expt 1 (most recent): goal attribution given utterance and heart-scale state

```{r warning=FALSE, message=FALSE, echo=FALSE, fig.width = 10, fig.height = 2.5}
ms$goal <- ordered(ms$goal, levels = c("honest", "nice", "mean"))
levels(ms$utterance) <- c("utterance: terrible", "utterance: bad","utterance: okay","utterance: good","utterance: amazing")

qplot(true_state, goal_prob, 
      colour = goal,
      data=ms) + 
  geom_line(aes(group=goal)) +
  facet_grid(.~utterance) +
  xlab("state") +
  ylab("likelihood for goal") +
 # ggtitle("Experiment: goals given heart-state and utterance") +
  geom_errorbar(aes(ymin=goal_prob-cil,ymax=goal_prob+cih,width=.1))

# comparison to model
model <- read.csv("/Users/ericang/Documents/Research/polgrice_GIT/model/results/goalsbda-politeRSA-sopt-alphaMH40000burn20000semantics-bern-50k-b25k.csv")

model <- model %>%
  mutate(true_state = State) %>%
  mutate(utterance = Utterance) %>%
  mutate(goal = Goal) %>%
  mutate(goal_prob = MAP) %>%
  mutate(cih = credHigh-MAP) %>%
  mutate(cil = MAP-credLow) %>%
  select(true_state, utterance, goal, goal_prob, cih, cil)
model$exp <- "model"
model$utterance <- ordered(model$utterance, levels = c("terrible", "bad", "okay", "good", "amazing"))
levels(model$utterance) <- c("utterance: terrible", "utterance: bad","utterance: okay","utterance: good","utterance: amazing")

ms$exp <- "experiment"

ms2 <- rbind(ms, model)

qplot(true_state, goal_prob, 
      colour = goal,
      data=ms2) + 
  geom_line(aes(group=goal)) +
  facet_grid(exp~utterance) +
  xlab("state") +
  ylab("likelihood for goal") +
 # ggtitle("Experiment: goals given heart-state and utterance") +
  geom_errorbar(aes(ymin=goal_prob-cil,ymax=goal_prob+cih,width=.1))
```
