---
title: "polgrice L2 S"
author: "Erica Yoon"
date: "Dec 3, 2015"
output: html_document
---

# expt

Given speaker goal and utterance, infer state

```{r warning=FALSE, message=FALSE, echo=FALSE}
rm(list = ls())
library(jsonlite)
library(ggplot2)
library(tidyr)
library(dplyr)
library(binom)
library(bootstrap)
library(langcog)
source("/Users/ericang/Documents/Research/polgrice_GIT/experiment/data_analysis/helper/useful.R")

raw.data.path <- "/Users/ericang/Documents/Research/polgrice_GIT/experiment/exp_versions/6_L2_S/production-results/"

## LOOP TO READ IN FILES
all.data <- data.frame()
files <- dir(raw.data.path,pattern="*.json")

for (file.name in files) {
  
  ## these are the two functions that are most meaningful
  json_file <- readLines(paste(raw.data.path,file.name,sep=""))
  json_file_str = paste(json_file, collapse = "")
  json_file_str = gsub(",}", "}", json_file_str)
  jso = jsonlite::fromJSON(json_file_str)
  jso$answers$data$people <- NULL
  jso1 <- data.frame(jso)
  jso1$subid <- substring(file.name, 1, 6)
  jso1$site <- "US"
  
  ## now here's where data get bound together
  all.data <- rbind(all.data, jso1)
}

d_us <- all.data %>%
  select(subid, site, answers.data.order, answers.data.knowledge, answers.data.domain, answers.data.goal, answers.data.utterance, answers.data.judgment)

raw.data.path <- "/Users/ericang/Documents/Research/polgrice_GIT/experiment/exp_versions/10_L2_S_India/production-results/"

## LOOP TO READ IN FILES
all.data <- data.frame()
files <- dir(raw.data.path,pattern="*.json")

for (file.name in files) {
  
  ## these are the two functions that are most meaningful
  json_file <- readLines(paste(raw.data.path,file.name,sep=""))
  json_file_str = paste(json_file, collapse = "")
  json_file_str = gsub(",}", "}", json_file_str)
  jso = jsonlite::fromJSON(json_file_str)
  jso$answers$data$people <- NULL
  jso1 <- data.frame(jso)
  jso1$subid <- substring(file.name, 1, 6)
  jso1$site <- "India"
  
  ## now here's where data get bound together
  all.data <- rbind(all.data, jso1)
}

d_india <- all.data %>%
  select(subid, site, answers.data.order, answers.data.knowledge, answers.data.domain, answers.data.goal, answers.data.utterance, answers.data.judgment)

all.data <- rbind(d_us, d_india)
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
d <- all.data %>%
  select(subid, site, answers.data.order, answers.data.knowledge, answers.data.domain, answers.data.goal, answers.data.utterance, answers.data.judgment)

d <- d %>%
  mutate(trial = answers.data.order) %>%
  mutate(item = answers.data.domain) %>%
  mutate(utterance = answers.data.utterance) %>%
  mutate(knowledge = answers.data.knowledge) %>%
  mutate(goal = answers.data.goal) %>%
  mutate(state = answers.data.judgment) %>%
  select(subid, site, trial, knowledge, utterance, goal, state)

d$subid <- as.factor(d$subid)
d$site <- as.factor(d$site)
d$trial <- as.numeric(d$trial)
d$state <- as.factor(d$state) 
d$knowledge <- as.factor(d$knowledge)
d$utterance <- as.factor(d$utterance)
d$goal <- as.factor(d$goal)
d$state <- as.numeric(d$state)

d$utterance <- ordered(d$utterance, levels = c("terrible", "bad", "okay", "good", "amazing"))
d$goal <- ordered(d$goal, levels = c("honest", "nice", "mean"))
```

```{r warning=FALSE, message=FALSE, echo=FALSE}
# goal_prob ~ true_state + utterance + goal
ms <- d %>%
  group_by(site, utterance, goal, subid) %>%
  summarize(
            state = mean(state, na.rm=TRUE)
          ) %>%
  group_by(site, utterance, goal) %>%
  multi_boot_standard(column = "state") %>%
  mutate(state = mean) %>%
  select(-mean)
```

## plot

```{r warning=FALSE, message=FALSE, echo=FALSE, fig.width = 10, fig.height = 2.5}
qplot(utterance, state, 
      colour = goal,
      shape = goal,
      data=ms) + 
  geom_line(aes(group=goal)) +
  facet_grid(.~site) +
  xlab("utterance") +
  ylab("inferred state") +
#  ggtitle("Inferred state given utterance and goal") +
  geom_errorbar(aes(ymin=ci_lower,ymax=ci_upper,width=.1))
```

## model comparison

```{r warning=FALSE, message=FALSE, echo=FALSE, fig.width = 10, fig.height = 2.5}

# comparison to model
model <- read.csv("/Users/ericang/Documents/Research/polgrice_GIT/model/results/bda-politeRSA-stateGivenUttGoal-goal3Vals-Beta50d-sopt-alpha-IncrMH100000burn50000semantics-bern-50k-b25ka.csv")

model <- model %>%
  mutate(utterance = Utterance) %>%
  mutate(goal = Goal) %>%
  mutate(state = MAP/20) %>%
  mutate(ci_upper = credHigh/20) %>%
  mutate(ci_lower = credLow/20) %>%
  select(utterance, goal, state, ci_upper, ci_lower)
model$site <- "model"
model$utterance <- ordered(model$utterance, levels = c("terrible", "bad", "okay", "good", "amazing"))
# levels(model$utterance) <- c("utterance: terrible", "utterance: bad","utterance: okay","utterance: good","utterance: amazing")
model$goal <- ordered(model$goal, levels = c("honest", "nice", "mean"))

levels(ms$utterance) <- c("terrible", "bad","okay","good","amazing")

ms2 <- rbind(ms, model)

qplot(utterance, state, 
      colour = goal,
      data=ms2) + 
  geom_line(aes(group=goal)) +
  facet_grid(.~site) +
  xlab("utterance") +
  ylab("inferred state") +
#  ggtitle("Inferred state given utterance and goal") +
  geom_errorbar(aes(ymin=ci_lower,ymax=ci_upper,width=.1))
```

# bootstrap

```{r}
# bootstrap function
bootstrap <- function(df, m) {
  n <- nrow(df)

  attr(df, "indices") <- replicate(m, sample(n, replace = TRUE) - 1, 
                                   simplify = FALSE)
  attr(df, "drop") <- TRUE
  attr(df, "group_sizes") <- rep(n, m)
  attr(df, "biggest_group_size") <- n
  attr(df, "labels") <- data.frame(replicate = 1:m)
  attr(df, "vars") <- list(quote(replicate))
  class(df) <- c("grouped_df", "tbl_df", "tbl", "data.frame")

  df
}
```

```{r}
nlsfit <- nls(state ~ k * goal + b, ms, start=list(k=1, b=0))
summary(nlsfit)

library(broom)
set.seed(2014)
bootnls <- ms %>% bootstrap(100) %>%
    do(tidy(nls(state ~ k * goal + b, ., start=list(k=1, b=0))))

```
